%% Spacecraft configuration for FINCH
spacecraft = struct( ...
    'mass',                 4.241487,                               ...
    'moi',                  [0.047380729, 0, 0;                     ...
                             0, 0.047380729, 0;                     ...
                             0, 0, 0.006473377],                    ...
    'fss1',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss2',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss3',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss4',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss5',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss6',                 struct(                                 ...
                            'type',     'fss-15',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'str',                  struct(                                 ...
                            'type',     'arcsec',                   ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm1',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm2',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm3',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm4',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm5',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm6',                 struct(                                 ...
                            'type',     'fss-15m',                  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'imu',                  struct(                                 ...
                            'type',     'adcs-10m-imu',             ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'gps',                  struct(                                 ...
                            'type',     'adcs-10m-gps',             ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq1',                 struct(                                 ...
                            'type',     'adcsmtq-core',             ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq2',                 struct(                                 ...
                            'type',     'adcsmtq-core',             ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq3',                 struct(                                 ...
                            'type',     'tensoradcs-mtq-air',       ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'cmg',                  struct(                                 ...
                            'type',     'cmg-10m-n',                ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            )                                       ...              
    );
[f_dir, ~, ~] = fileparts(mfilename('fullpath'));
save_path = fullfile(f_dir, 'finch.mat');
save(save_path, 'spacecraft');