%% Spacecraft configuration for FINCH
spacecraft = struct( ...
    'mass',                 4.241487,                               ...
    'moi',                  [0.047380729, 0, 0;                     ...
                             0, 0.047380729, 0;                     ...
                             0, 0, 0.006473377],                    ...
    'moi_inv',              inv([0.047380729, 0, 0;                 ...
                                 0, 0.047380729, 0;                 ...
                                 0, 0, 0.006473377]),               ...
    'fss1',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss2',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss3',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss4',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss5',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'fss6',                 struct(                                 ...
                            'obj',      load('fss-15.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'str',                  struct(                                 ...
                            'obj',      load('arcsec.mat').sensor,  ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtm1',                 struct(                                 ...
                            'obj',      load('fss-15m.mat').sensor, ...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'imu',                  struct(                                 ...
                            'obj',      load('adcs-10m-imu.mat').sensor,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'gps',                  struct(                                 ...
                            'obj',      load('adcs-10m-gps.mat').sensor,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq1',                 struct(                                 ...
                            'obj',      load('adcsmtq-core.mat').actuator,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq2',                 struct(                                 ...
                            'obj',      load('adcsmtq-core.mat').actuator,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'mtq3',                 struct(                                 ...
                            'obj',      load('adcsmtq-air.mat').actuator,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            ),                                      ...
    'cmg',                  struct(                                 ...
                            'obj',      load('cmg-10m-n.mat').actuator,...
                            'origin',   [0, 0, 0],                  ...
                            'dcm',      [1, 0, 0; 0, 1, 0; 0, 0, 1] ...
                            )                                       ...              
    );
[f_dir, ~, ~] = fileparts(mfilename('fullpath'));
save_path = fullfile(f_dir, 'finch.mat');
save(save_path, 'spacecraft');