% FINCH-style spacecraft compatibility struct derived from init_adcs_params.m.

spacecraft = struct( ...
    'name', 'finch', ...
    'mass_kg', mass_sc, ...
    'dimensions_m', struct( ...
        'x', sc_dim_x, ...
        'y', sc_dim_y, ...
        'z', sc_dim_z), ...
    'inertia_kgm2', J, ...
    'initial_conditions', struct( ...
        'q0', q0, ...
        'omega0_radps', omega0, ...
        'wheel_momentum0_Nms', h_W0), ...
    'faces', struct( ...
        'normals_body', sc_face_normals, ...
        'areas_m2', sc_face_areas, ...
        'cop_body_m', sc_face_cop), ...
    'sensor_mounts', struct( ...
        'fss_boresights_body', fss_boresights, ...
        'star_tracker_boresight_body', st_boresight), ...
    'actuator_layout', struct( ...
        'reaction_wheel_axes_body', rw_axes, ...
        'magnetorquer_axes_body', mtq_axes));
