[project]
name = "adcs-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=8.0.1",
    "imageio>=2.37.4",
    "pydantic>=2.13.4",
    "vispy>=0.16.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]