function cfg = sim_config()
%SIM_CONFIG Build a structured compatibility view of the simulator config.
%
%   CFG = SIM_CONFIG() derives grouped spacecraft, orbit, sensor, actuator,
%   control, and environment data from init_adcs_params.m. This provides a
%   sim-finch-style configuration entrypoint without introducing a second
%   parameter source alongside the live Simulink model inputs.

    repo_root = fileparts(mfilename('fullpath'));
    prev_dir = pwd;
    cleanup = onCleanup(@() cd(prev_dir)); %#ok<NASGU>
    cd(repo_root);

    run(fullfile(repo_root, 'init_adcs_params.m'));
    run(fullfile(repo_root, 'sim_config', 'sensor_params', 'catalog.m'));
    run(fullfile(repo_root, 'sim_config', 'actuator_params', 'catalog.m'));
    run(fullfile(repo_root, 'sim_config', 'spacecraft', 'finch.m'));

    cfg = struct( ...
        'simulation', struct( ...
            't0', 0, ...
            'tf', t_end, ...
            'dt', dt, ...
            'solver', 'ode4'), ...
        'spacecraft', spacecraft, ...
        'orbit', struct( ...
            'R_earth', R_earth, ...
            'mu_earth', mu_earth, ...
            'J2_earth', J2_earth, ...
            'omega_earth', omega_earth, ...
            'altitude_m', orbit_alt, ...
            'inclination_deg', orbit_inc, ...
            'eccentricity', orbit_ecc, ...
            'raan_deg', orbit_RAAN, ...
            'argument_of_perigee_deg', orbit_AOP, ...
            'true_anomaly_deg', orbit_TA, ...
            'semi_major_axis_m', orbit_a, ...
            'period_s', orbit_period, ...
            'mean_motion_radps', orbit_n), ...
        'environment', struct( ...
            'epoch_jd', epoch_jd, ...
            'ephemeris_csv', ephem_csv, ...
            'mag_field_equatorial_T', B0_earth, ...
            'solar_pressure_1au_Npm2', solar_pressure_1au, ...
            'atmosphere', struct( ...
                'ref_altitude_m', atm_ref_alt, ...
                'ref_density_kgpm3', atm_ref_density, ...
                'scale_height_m', atm_scale_height), ...
            'drag_coeff', drag_coeff, ...
            'srp_coeff', srp_coeff, ...
            'residual_dipole_Am2', residual_dipole), ...
        'sensors', sensor_catalog, ...
        'actuators', actuator_catalog, ...
        'control', struct( ...
            'rw_kp', ctrl_rw_kp, ...
            'rw_kd', ctrl_rw_kd, ...
            'bdot_gain', ctrl_bdot_gain, ...
            'dump_gain', ctrl_dump_gain, ...
            'unload_fraction', ctrl_unload_fraction, ...
            'mode_detumble_rate_radps', mode_detumble_rate, ...
            'mode_fine_rate_radps', mode_fine_rate, ...
            'mode_fine_err_rad', mode_fine_err), ...
        'estimation', struct( ...
            'mekf_sigma_g', mekf_sigma_g, ...
            'mekf_sigma_b', mekf_sigma_b, ...
            'mekf_sun_sigma', mekf_sun_sigma, ...
            'mekf_mag_sigma', mekf_mag_sigma));
end
