% Sensor catalog derived from init_adcs_params.m.

sensor_catalog = struct( ...
    'fine_sun_sensor', struct( ...
        'count', fss_num, ...
        'noise_sigma_deg', fss_noise_sigma, ...
        'fov_half_angle_deg', fss_fov_half, ...
        'sample_rate_hz', fss_sample_rate, ...
        'boresights_body', fss_boresights), ...
    'star_tracker', struct( ...
        'noise_boresight_arcsec', st_noise_bore, ...
        'noise_roll_arcsec', st_noise_roll, ...
        'sample_rate_hz', st_sample_rate, ...
        'exclusion_sun_deg', st_exclusion_sun, ...
        'exclusion_moon_deg', st_exclusion_moon, ...
        'exclusion_earth_deg', st_exclusion_earth, ...
        'boresight_body', st_boresight), ...
    'imu', struct( ...
        'angular_random_walk_deg_per_sqrt_s', imu_arw, ...
        'bias_instability_deg_per_hr', imu_bias_instab, ...
        'sample_rate_hz', imu_sample_rate, ...
        'range_deg_per_s', imu_range), ...
    'magnetometer', struct( ...
        'noise_sigma_nT', mag_noise_sigma, ...
        'bias_nT', mag_bias, ...
        'sample_rate_hz', mag_sample_rate), ...
    'gnss', struct( ...
        'position_sigma_m', gnss_pos_sigma, ...
        'velocity_sigma_mps', gnss_vel_sigma, ...
        'sample_rate_hz', gnss_sample_rate));
