% Actuator catalog derived from init_adcs_params.m.

actuator_catalog = struct( ...
    'reaction_wheel', struct( ...
        'count', rw_num, ...
        'max_torque_Nm', rw_max_torque, ...
        'max_momentum_Nms', rw_max_momentum, ...
        'max_speed_rpm', rw_max_speed, ...
        'rotor_inertia_kgm2', rw_inertia, ...
        'axes_body', rw_axes), ...
    'magnetorquer', struct( ...
        'count', mtq_num, ...
        'max_dipole_Am2', mtq_max_dipole, ...
        'axes_body', mtq_axes), ...
    'cmg', struct( ...
        'count', 1, ...
        'max_torque_Nm', cmg_max_torque, ...
        'stored_momentum_Nms', cmg_momentum, ...
        'max_gimbal_rate_radps', cmg_gimbal_rate));
